import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "2048",
  description: "2048 Game generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
